{
 "title": "Ledger Exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Summary (all time)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ledger_total_assets", "legendFormat": "currently in {{currency}}" },
    { "expr": "-1 * ledger_total_income", "legendFormat": "income in {{currency}}" },
    { "expr": "ledger_total_expenses", "legendFormat": "Expenses in {{currency}}" }
   ]
  },
  {
   "title": "This month's expenses by category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category,currency) (ledger_expenses_monthly{month_tag=\"current\"})",
     "legendFormat": "{{category}} - {{currency}}"
    }
   ]
  },
  {
   "title": "last month's expenses by category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category,currency) (ledger_expenses_monthly{month_tag=\"previous\"})",
     "legendFormat": "{{category}} - {{currency}}"
    }
   ]
  },
  {
   "title": "expenses by category (all time)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledger_expenses{currency=\"EUR\"}",
     "legendFormat": "{{category}} - {{currency}}"
    }
   ]
  },
  {
   "title": "Expenses per month",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (currency, month) (ledger_expenses_monthly)",
     "legendFormat": "{{month}} - {{currency}}"
    }
   ]
  },
  {
   "title": "Top 40 expenses for this month",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(40, ledger_expense_by_payee{month_tag=\"current\"})",
     "legendFormat": "{{payee}}"
    }
   ]
  },
  {
   "title": "Top 40 last month's expenses",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(40, ledger_expense_by_payee{month_tag=\"previous\"})",
     "legendFormat": "{{payee}}"
    }
   ]
  },
  {
   "title": "Top 40 expenses (all time)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(40, sum by (payee) (ledger_expense_by_payee))\n",
     "legendFormat": "{{payee}}"
    }
   ]
  }
 ]
}